create table if not exists production.star."Customer Order History" (
-- create or replace table production.star."Customer Order History" (
     "Business Unit" varchar(50) comment 'Business unit to which the order belongs'
    , "Carrier" varchar(150) comment 'Carrier used for shipping products to the customer'
    , "Create Date" timestamp_ntz(9) comment 'Date when the original order was created'
    , "Credit Terms" varchar(100) comment 'Terms of credit payment for the order'
    , "Currency" varchar(100) comment 'Currency in which the order is denominated'
    , "Customer Key" number comment 'Unique identifier for the customer'
    , "Customer Number" number(38, 0) comment 'Unique identifier for customer'
    , "Customer PO" varchar(100) comment 'Customer purchase order number'
    , "Customer SKU" varchar(100) comment 'Stock keeping unit assigned by the customer to the product'
    , "Due Date" date comment 'Date when the order is due to ship'
    , "Effective Date" timestamp_ntz(9) comment 'Date when the order took effect'
    , "Entered By" varchar(100) comment 'User who entered the order'
    , "Euro Exchange Rate" number(38, 10) comment 'Exchange rate for converting the order to euros'
    , "Extended Price" number(38, 2) comment 'Total price of the line item'
    , "Incoterms" varchar(150) comment 'Shipment and delivery responsibilities between the buyer and seller'
    , "Key" number comment 'Unique identifier for the order'
    , "Language" varchar(25) comment 'Language in which the order is written'
    , "Last Shipped Date" date comment 'Date when the last shipment was made'
    , "Line Number" number(38, 1) comment 'Unique identifier of the specific line within the order'
    , "Order Date" date comment 'Date when the order was placed'
    , "Order Number" number(10, 0) comment 'Unique identifier of the order'
    , "Product Key" number comment 'Unique identifier for the product'
    , "Quantity Cancelled" number(38, 3) comment 'Number of units cancelled from the order'
    , "Quantity Ordered" number(38, 3) comment 'Number of units ordered by the customer'
    , "Quantity Shipped" number(38, 3) comment 'Number of units shipped to the customer'
    , "Quote Line" number(38, 1) comment 'Unique identifier of the line item in the quote'
    , "Quote Number" number(10, 0) comment 'Unique identifier of the quote associated with the order'
    , "Reference Number" number(10, 0) comment 'Unique identifier for cross-referencing related documents'
    , "Salesperson" varchar(150) comment 'Assigned sales representative'
    , "Ship To Number" number(38, 0) comment 'Unique identifier of ship to associated with the order'
    , "Ship To Key" number comment 'Unique identifier for the ship to'
    , "SKU" varchar(50) comment 'Stock keeping unit assigned by the company to the product'
    , "Status" varchar(10) comment 'Identifies the order as active or inactive'
    , "Unit Price" number(38, 5) comment 'Price per unit of the line item'
	, constraint CustomerOrderHistoryPK primary key ("Key")
)
    comment = 'History of changes to customer order records'
;