create table if not exists production.star."Product History" (
-- create or replace table production.star."Product History" (
    "ABC Code" varchar(1) comment 'Classifies products based on their contribution to revenue or profit'
    , "Bauart 1" varchar(100) comment 'Business unit specific product classification'
    , "Bauart 2" varchar(100) comment 'Business unit specific product classification'
    , "Bauart 3" varchar(100) comment 'Business unit specific product classification'
    , "Bauart 4" varchar(100) comment 'Business unit specific product classification'
    , "Business Unit" varchar(50) comment 'Business unit to which the product belongs'
    , "Country of Origin (English)" varchar(100) comment 'Where the product is manufactured or produced'
    , "Country of Origin (German)" varchar(100) comment 'Where the product is manufactured or produced'
    , "Create Date" timestamp_ntz(9) comment 'Date when the original product record was created'
    , "Current Record" boolean comment 'Indicates if the record is the most recent and active entry for the product'
    , "Description (English)" varchar(255) comment 'Description of product'
    , "Description (German)" varchar(255) comment 'Description of product'
    , "Effective Date" timestamp_ntz(9) comment 'Date when this version of product record took effect'
    , "Expiration Date" timestamp_ntz(9) comment 'Date when this version of product record expires'
    , "Family" varchar(50) comment 'Highest level in product classification hierarchy'
    , "Height" number(38,5) comment 'Height of a single unit of product'
    , "Height Unit of Measure (English)" varchar(50) comment 'Standard unit for quantifying product height'
    , "Height Unit of Measure (German)" varchar(50) comment 'Standard unit for quantifying product height'
    , "HS Code" varchar(50) comment 'Harmonized system code for international trade classification'
    , "Inventory Type" varchar(50) comment 'Identifies product as Raw, Work in Process, or Finished Good'
    , "Key" number comment 'Unique identifier for current version of product'
    , "Length" number(38,5) comment 'Length of a single unit of product'
    , "Length Unit of Measure (English)" varchar(50) comment 'Standard unit for quantifying product length'
    , "Length Unit of Measure (German)" varchar(50) comment 'Standard unit for quantifying product length'
    , "Line" varchar(50) comment 'Mid level in product classification hierarchy'
    , "SKU" varchar(50) comment 'Unique identifier for product'
    , "Source" varchar(50) comment 'Indicates how the product is obtained or produced'
    , "Status" varchar(10) comment 'Identifies the product as active or inactive'
    , "Stocked Flag" varchar(50) comment 'Indicates whether product is regularly stocked or not'
    , "Type" varchar(50) comment 'Lowest level in product classification hierarchy'
    , "Unit of Measure (English)" varchar(50) comment 'Standard unit for quantifying product'
    , "Unit of Measure (German)" varchar(50) comment 'Standard unit for quantifying product'
    , "Vendor" varchar(10) comment 'Primary supplier of product'
    , "Weight" number(38,5) comment 'Weight of a single unit of product'
    , "Weight Unit of Measure (English)" varchar(50) comment 'Standard unit for quantifying product weight'
    , "Weight Unit of Measure (German)" varchar(50) comment 'Standard unit for quantifying product weight'
    , "Width" number(38,5) comment 'Weight of a single unit of product'
    , "Width Unit of Measure (English)" varchar(50) comment 'Standard unit for quantifying product weight'
    , "Width Unit of Measure (German)" varchar(50) comment 'Standard unit for quantifying product weight'
    , constraint "ProductHistoryPK" primary key ("Key")
)
    comment = 'History of changes to records in the product dimension'
;