create table if not exists production.star."Ship To" (
-- create or replace table production.star."Ship To" (
    "Address Line 1" varchar(100) comment 'First line of street address',
    "Address Line 2" varchar(100) comment 'Second line of street address',
    "Address Line 3" varchar(100) comment 'Third line of street address',
    "Address Line 4" varchar(100) comment 'Fourth line of street address',
    "Business Unit" varchar(50) comment 'Business unit to which the ship to belongs',
    "Carrier (English)" varchar(150) comment 'Shipping carrier or logistics provider',
    "Carrier (German)" varchar(150) comment 'Shipping carrier or logistics provider',
    "City" varchar(250) comment 'City where the ship to is located',
    "Country (English)" varchar(100) comment 'Country where the ship to is located',
    "Country (German)" varchar(100) comment 'Country where the ship to is located',
    "Create Date" timestamp_ntz(9) comment 'Date when the original ship to record was created',
    "Currency" varchar(50) comment 'Preferred currency for transactions',
    "Customer Number" number(38, 0) comment 'Unique identifier for customer associated with the ship to record',
    "Effective Date" timestamp_ntz(9) comment 'Date when current version of ship to record took effect',
    "Fax Number" varchar(50) comment 'Primary contact number for communicating via fax',
    "Incoterms (English)" varchar(150) comment 'Shipping responsibilities between the buyer and seller',
    "Incoterms (German)" varchar(150) comment 'Shipping responsibilities between the buyer and seller',
    "Key" number(38, 0) comment 'Unique identifier for current version of ship to',
    "Language" varchar(50) comment 'Preferred communication language',
    "Latitude" number(38,5) comment 'Geographic coordinate of north-south position on Earth''s surface',
    "Longitude" number(38,5) comment 'Geographic coordinate of east-west position on Earth''s surface',
    "Name" varchar(250) comment 'Name of the ship to',
    "Phone Number" varchar(50) comment 'Phone number for the ship to',
    "Postal Code" varchar(25) comment 'Primary contact number for communicating via phone',
    "Salesperson" varchar(150) comment 'Assigned sales representative',
    "Ship To Number" number(38, 0) comment 'Unique identifier for ship to associated with the customer record',
    "State/Province" varchar(100) comment 'State or province where the ship to is located',
    "Status" varchar(10) comment 'Identifies the ship to as active or inactive',
    "Tax ID" varchar(50) comment 'Official tax identification number',
    "Tax ID Type" varchar(50) comment 'Category or classification of the tax ID',
    "Type" varchar(100) comment 'Type of ship to',
    constraint "ShipToPK" primary key ("Customer Number", "Ship To Number")
)
    comment = 'Current version of records in the ship to dimension';